name: safe_nav
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.6.1   # <-- Add this line
  firebase_core: ^2.25.4
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1
  geolocator: ^10.1.0
  image_picker: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
