// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARH2nx5gZYHkKECRaPbbVvr5CWgsLSLpE',
    appId: '1:847249321188:web:c55fd9108df78213b850f1',
    messagingSenderId: '847249321188',
    projectId: 'safenav-f505c',
    authDomain: 'safenav-f505c.firebaseapp.com',
    storageBucket: 'safenav-f505c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY10jPChQ1TV5-swnlCQ5yYz3pWshZwrU',
    appId: '1:847249321188:android:459284731bc451feb850f1',
    messagingSenderId: '847249321188',
    projectId: 'safenav-f505c',
    storageBucket: 'safenav-f505c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEg7knp9TXCFvxVQEtZ-e4jCpH64f_Rio',
    appId: '1:847249321188:ios:6b759bccaf5133b5b850f1',
    messagingSenderId: '847249321188',
    projectId: 'safenav-f505c',
    storageBucket: 'safenav-f505c.firebasestorage.app',
    iosBundleId: 'com.example.safeNav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEg7knp9TXCFvxVQEtZ-e4jCpH64f_Rio',
    appId: '1:847249321188:ios:6b759bccaf5133b5b850f1',
    messagingSenderId: '847249321188',
    projectId: 'safenav-f505c',
    storageBucket: 'safenav-f505c.firebasestorage.app',
    iosBundleId: 'com.example.safeNav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARH2nx5gZYHkKECRaPbbVvr5CWgsLSLpE',
    appId: '1:847249321188:web:8875972d5b518e40b850f1',
    messagingSenderId: '847249321188',
    projectId: 'safenav-f505c',
    authDomain: 'safenav-f505c.firebaseapp.com',
    storageBucket: 'safenav-f505c.firebasestorage.app',
  );
}
